---
- name: install useful packages
  apt:
    name:
      - acl
      - vim
      - git
      - git-extras
      - tmux
      - python-setuptools
      - virtualenv
      - python-pip
    state: present
    force_apt_get: yes
  become: yes
  tags:
    - install
