---
- include_vars: ../../users/vars/main.yml
  tags:
    - always

- name: install docker package
  apt:
    name: docker.io
    state: present
    force_apt_get: yes
  become: yes
  tags:
    - install-docker    

- name: ensure group docker exists
  group:
    name: docker
    state: present
  become: yes
  tags:
    - add-group-docker

- name: ensure nreymond user in docker group
  user:
    name: nreymond
    append: yes
    groups: docker
    state: present
  become: yes
  tags:
    - add-dojo-group-docker
    - add_all_user_dockergroup


- name: ensure main users in docker group
  user:
    name: "{{ item.name }}"
    append: yes
    groups: docker
    state: present
  become: yes
  with_items: "{{ vmusers }}"
  tags:
    - add-main-group-docker
    - add_all_user_dockergroup

- name: install docker package
  apt:
    name: docker.io
    state: present
    force_apt_get: yes
  become: yes
  tags:
    - install-docker

- name: remove pip docker-py
  pip:
    name: docker-py
    state: absent
  become: yes

- name: install docker for pip
  pip:
    name: docker
    state: present
  become: yes

- name: start service docker, if not started
  service:
    name: docker
    state: started
  become: yes
  tags:
    - start-docker-service

- name: create prometheus config folder
  file:
    path: /etc/prometheus
    state: directory

- name: create prometheus config file
  copy:
    dest: /etc/prometheus/prometheus.yml
    content: |
      # ToDO


- name: deploy inline template
  copy:
    content: '<html><head><title>Hello</title></head><body><h1>Hello World!</h1></body></html>'
    dest: /srv/web/index.html

- name: test docker
  docker_container:
    name: test-prometheus-hello-world
    state: started
    image: prom/prometheus:v2.1.0
    volumes:
      - /etc/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
  
